version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kubeci
    container_name: kubeci
    env_file:
      - .env
    volumes:
      - ./script.sh:/usr/local/bin/kubci